import QRCode from 'qrcode';
import { isNative, saveAndShareImage } from './native';

export async function qrDataUrl(text: string, width = 512): Promise<string> {
  return QRCode.toDataURL(text, {
    width,
    margin: 1,
    errorCorrectionLevel: 'M',
    color: { dark: '#1c1813', light: '#ffffff' },
  });
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

export interface QrCardData {
  index: number; // 0-based
  total: number; // count
  amount: number;
  upiId: string;
  receiverName: string;
  note: string;
  uri: string;
}

/** Build a premium branded PNG (1080x1350) and trigger download. */
export async function downloadBrandedQr(card: QrCardData): Promise<'saved' | 'shared' | 'failed'> {
  const W = 1080;
  const H = 1350;
  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Canvas not supported');

  // Background
  const bg = ctx.createLinearGradient(0, 0, 0, H);
  bg.addColorStop(0, '#ffffff');
  bg.addColorStop(1, '#f4f0e6');
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  // Top brand bar
  ctx.fillStyle = '#173b2e';
  ctx.fillRect(0, 0, W, 14);

  const pad = 72;
  let y = 84;

  // Brand
  ctx.fillStyle = '#173b2e';
  ctx.font = '800 40px Inter, system-ui, sans-serif';
  ctx.fillText('SplitUPI', pad, y);
  ctx.fillStyle = '#6b7280';
  ctx.font = '500 30px Inter, system-ui, sans-serif';
  ctx.textAlign = 'right';
  ctx.fillText(`Payment ${card.index + 1} of ${card.total}`, W - pad, y);
  ctx.textAlign = 'left';

  y += 28;
  ctx.strokeStyle = '#e4d9b8';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(pad, y);
  ctx.lineTo(W - pad, y);
  ctx.stroke();

  // Receiver
  y += 70;
  ctx.fillStyle = '#1c1813';
  ctx.font = '700 52px Inter, system-ui, sans-serif';
  ctx.fillText(card.receiverName.slice(0, 28), pad, y);
  y += 52;
  ctx.fillStyle = '#6b7280';
  ctx.font = '500 34px Inter, system-ui, sans-serif';
  ctx.fillText(card.upiId.slice(0, 40), pad, y);

  // QR box
  y += 44;
  const boxY = y;
  const boxH = 660;
  ctx.fillStyle = '#ffffff';
  ctx.strokeStyle = '#e5e7eb';
  ctx.lineWidth = 3;
  roundRect(ctx, pad, boxY, W - pad * 2, boxH, 36);
  ctx.fill();
  ctx.stroke();

  const qr = await qrDataUrl(card.uri, 720);
  const img = await loadImage(qr);
  const qrSize = 560;
  const qx = (W - qrSize) / 2;
  const qy = boxY + 50;
  ctx.drawImage(img, qx, qy, qrSize, qrSize);

  // Amount inside box
  ctx.fillStyle = '#1c1813';
  ctx.textAlign = 'center';
  ctx.font = '800 62px Inter, system-ui, sans-serif';
  const amt = `₹${card.amount.toLocaleString('en-IN', { minimumFractionDigits: card.amount % 1 === 0 ? 0 : 2, maximumFractionDigits: 2 })}`;
  ctx.fillText(amt, W / 2, boxY + boxH - 36);
  ctx.textAlign = 'left';

  // Note + footer
  y = boxY + boxH + 64;
  if (card.note.trim()) {
    ctx.fillStyle = '#4b5563';
    ctx.font = '500 32px Inter, system-ui, sans-serif';
    ctx.fillText(`Note: ${card.note.slice(0, 48)}`, pad, y);
    y += 52;
  }
  ctx.fillStyle = '#7a7264';
  ctx.font = '500 28px Inter, system-ui, sans-serif';
  ctx.fillText('Scan with any UPI app to pay • Generated by SplitUPI', pad, y);

  const filename = `splitupi-${card.index + 1}-of-${card.total}-rs${String(card.amount).replace('.', 'p')}.png`;
  const png = canvas.toDataURL('image/png');
  if (isNative()) return saveAndShareImage(png, filename);
  const a = document.createElement('a');
  a.download = filename;
  a.href = png;
  document.body.appendChild(a);
  a.click();
  a.remove();
  return 'saved';
}

export function downloadDataUrl(dataUrl: string, filename: string) {
  const a = document.createElement('a');
  a.href = dataUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      ta.remove();
      return true;
    } catch {
      return false;
    }
  }
}

export async function shareText(title: string, text: string, url?: string): Promise<'shared' | 'copied' | 'unsupported'> {
  const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void>; canShare?: (d: ShareData) => boolean };
  if (nav.share) {
    try {
      const data: ShareData = { title, text };
      if (url) {
        // Only attach url if share supports it; UPI URIs may not be shareable as URL everywhere
        if (!nav.canShare || nav.canShare({ ...data, url: 'https://example.com' })) {
          // keep UPI link inside text instead to be safe
        }
      }
      await nav.share(data);
      return 'shared';
    } catch (e) {
      if ((e as Error)?.name === 'AbortError') return 'shared'; // dismissed = fine
    }
  }
  const ok = await copyText(text);
  return ok ? 'copied' : 'unsupported';
}
